version: "3.8"

services:
  flask_app:
    build:
      context: .
      dockerfile: server/Dockerfile # Correct path to Dockerfile
    ports:
      - "5000:5000" # Maps container's port 5000 to the host
    volumes:
      - ./server:/app # Mounts the local `server` directory into the container
    environment:
      - FLASK_ENV=development # Enables Flask debug mode
    restart: always # Ensures the container restarts if it crashes

  vue:
    build:
      context: ./client # Ensure it points to the client directory
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"

networks:
  app_network:
    driver: bridge
